import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'

const eslintConfig = [
  ...nextCoreWebVitals,
  {
    // lib/furigana-wasm is generated by wasm/build.sh
    ignores: ['.next/**', 'node_modules/**', 'public/**', 'lib/furigana-wasm/**', 'wasm/target/**'],
  },
]

export default eslintConfig
